apiVersion: v1
kind: Secret
metadata:
  name: sidecar-logger-elasticsearch
  # namespace: default  
type: Opaque
stringData:
  ES_HOST: "<elasticsearch-host>"          # e.g. elasticsearch.example.com
  ES_PORT: "443"
  ES_USER: "<username>"
  ES_PASSWORD: "<password>"
  ES_INDEX_PREFIX: "sample-app-logs"     # creates indices: sample-app-logs-YYYY.MM.DD
  ES_TLS: "On"                           